#############################################################################
# Makefile for building: robotino1
# Generated by qmake (2.01a) (Qt 4.7.1) on: Di. Feb 28 14:37:17 2012
# Project:  robotino1.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile robotino1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fPIC -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include -I/mnt/LaCie/Alex/OpenRobotinoAPI64/1/include -I/usr/local/qwt-6.0.0/include -I/usr/include/opencv -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib64 -Wl,-rpath,/mnt/LaCie/Alex/OpenRobotinoAPI64/1/lib/linux -L/usr/local/qwt-6.0.0/lib -lqwt -L/mnt/LaCie/Alex/OpenRobotinoAPI64/1/lib/linux -lrec_robotino_com `pkg-config --libs opencv` -lQtGui -L/usr/lib64 -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		robotinowindow.cpp \
		distancesensorview.cpp \
		accelerometerview.cpp \
		robotinoinfo.cpp \
		powerview.cpp \
		robotino.cpp \
		robotinocamera.cpp \
		robotinoaudio.cpp \
		audioview.cpp \
		robotinofeaturewindow.cpp \
		cameraview.cpp \
		smcwindow.cpp \
		smcthread.cpp \
		actionobservationview.cpp \
		imageseqview.cpp \
		actionvalueview.cpp moc_mainwindow.cpp \
		moc_robotinowindow.cpp \
		moc_distancesensorview.cpp \
		moc_accelerometerview.cpp \
		moc_powerview.cpp \
		moc_robotino.cpp \
		moc_robotinocamera.cpp \
		moc_robotinoaudio.cpp \
		moc_audioview.cpp \
		moc_robotinofeaturewindow.cpp \
		moc_cameraview.cpp \
		moc_smcwindow.cpp \
		moc_smcthread.cpp \
		moc_actionobservationview.cpp \
		moc_imageseqview.cpp \
		moc_actionvalueview.cpp \
		qrc_robotino-ressources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		robotinowindow.o \
		distancesensorview.o \
		accelerometerview.o \
		robotinoinfo.o \
		powerview.o \
		robotino.o \
		robotinocamera.o \
		robotinoaudio.o \
		audioview.o \
		robotinofeaturewindow.o \
		cameraview.o \
		smcwindow.o \
		smcthread.o \
		actionobservationview.o \
		imageseqview.o \
		actionvalueview.o \
		moc_mainwindow.o \
		moc_robotinowindow.o \
		moc_distancesensorview.o \
		moc_accelerometerview.o \
		moc_powerview.o \
		moc_robotino.o \
		moc_robotinocamera.o \
		moc_robotinoaudio.o \
		moc_audioview.o \
		moc_robotinofeaturewindow.o \
		moc_cameraview.o \
		moc_smcwindow.o \
		moc_smcthread.o \
		moc_actionobservationview.o \
		moc_imageseqview.o \
		moc_actionvalueview.o \
		qrc_robotino-ressources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		robotino1.pro
QMAKE_TARGET  = robotino1
DESTDIR       = 
TARGET        = robotino1

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_robotinowindow.h ui_robotinofeaturewindow.h ui_smcwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: robotino1.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl \
		/usr/lib64/libQtNetwork.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile robotino1.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
/usr/lib64/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile robotino1.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/robotino11.0.0 || $(MKDIR) .tmp/robotino11.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/robotino11.0.0/ && $(COPY_FILE) --parents mainwindow.h robotinowindow.h distancesensorview.h accelerometerview.h robotinoinfo.h powerview.h robotino.h robotinocamera.h robotinoaudio.h audioview.h robotinofeaturewindow.h cameraview.h smcwindow.h smcthread.h actionobservationview.h imageseqview.h actionvalueview.h .tmp/robotino11.0.0/ && $(COPY_FILE) --parents robotino-ressources.qrc .tmp/robotino11.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp robotinowindow.cpp distancesensorview.cpp accelerometerview.cpp robotinoinfo.cpp powerview.cpp robotino.cpp robotinocamera.cpp robotinoaudio.cpp audioview.cpp robotinofeaturewindow.cpp cameraview.cpp smcwindow.cpp smcthread.cpp actionobservationview.cpp imageseqview.cpp actionvalueview.cpp .tmp/robotino11.0.0/ && $(COPY_FILE) --parents mainwindow.ui robotinowindow.ui robotinofeaturewindow.ui smcwindow.ui .tmp/robotino11.0.0/ && (cd `dirname .tmp/robotino11.0.0` && $(TAR) robotino11.0.0.tar robotino11.0.0 && $(COMPRESS) robotino11.0.0.tar) && $(MOVE) `dirname .tmp/robotino11.0.0`/robotino11.0.0.tar.gz . && $(DEL_FILE) -r .tmp/robotino11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_robotinowindow.cpp moc_distancesensorview.cpp moc_accelerometerview.cpp moc_powerview.cpp moc_robotino.cpp moc_robotinocamera.cpp moc_robotinoaudio.cpp moc_audioview.cpp moc_robotinofeaturewindow.cpp moc_cameraview.cpp moc_smcwindow.cpp moc_smcthread.cpp moc_actionobservationview.cpp moc_imageseqview.cpp moc_actionvalueview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_robotinowindow.cpp moc_distancesensorview.cpp moc_accelerometerview.cpp moc_powerview.cpp moc_robotino.cpp moc_robotinocamera.cpp moc_robotinoaudio.cpp moc_audioview.cpp moc_robotinofeaturewindow.cpp moc_cameraview.cpp moc_smcwindow.cpp moc_smcthread.cpp moc_actionobservationview.cpp moc_imageseqview.cpp moc_actionvalueview.cpp
moc_mainwindow.cpp: smcthread.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_robotinowindow.cpp: robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h \
		cameraview.h \
		audioview.h \
		accelerometerview.h \
		distancesensorview.h \
		powerview.h \
		robotinowindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) robotinowindow.h -o moc_robotinowindow.cpp

moc_distancesensorview.cpp: distancesensorview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) distancesensorview.h -o moc_distancesensorview.cpp

moc_accelerometerview.cpp: accelerometerview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) accelerometerview.h -o moc_accelerometerview.cpp

moc_powerview.cpp: powerview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) powerview.h -o moc_powerview.cpp

moc_robotino.cpp: robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h \
		robotino.h
	/usr/bin/moc $(DEFINES) $(INCPATH) robotino.h -o moc_robotino.cpp

moc_robotinocamera.cpp: robotinocamera.h
	/usr/bin/moc $(DEFINES) $(INCPATH) robotinocamera.h -o moc_robotinocamera.cpp

moc_robotinoaudio.cpp: robotinoaudio.h
	/usr/bin/moc $(DEFINES) $(INCPATH) robotinoaudio.h -o moc_robotinoaudio.cpp

moc_audioview.cpp: audioview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) audioview.h -o moc_audioview.cpp

moc_robotinofeaturewindow.cpp: audioview.h \
		robotinofeaturewindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) robotinofeaturewindow.h -o moc_robotinofeaturewindow.cpp

moc_cameraview.cpp: cameraview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cameraview.h -o moc_cameraview.cpp

moc_smcwindow.cpp: smcwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) smcwindow.h -o moc_smcwindow.cpp

moc_smcthread.cpp: smcthread.h
	/usr/bin/moc $(DEFINES) $(INCPATH) smcthread.h -o moc_smcthread.cpp

moc_actionobservationview.cpp: actionobservationview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) actionobservationview.h -o moc_actionobservationview.cpp

moc_imageseqview.cpp: imageseqview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) imageseqview.h -o moc_imageseqview.cpp

moc_actionvalueview.cpp: smcthread.h \
		actionvalueview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) actionvalueview.h -o moc_actionvalueview.cpp

compiler_rcc_make_all: qrc_robotino-ressources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_robotino-ressources.cpp
qrc_robotino-ressources.cpp: robotino-ressources.qrc \
		robotino-icon.png \
		robertino.png \
		icons/task-reject.png \
		icons/arrow-down.png \
		icons/office-chart-bar.png \
		icons/media-playback-pause.png \
		icons/arrow-ccl.png \
		icons/arrow-up.png \
		icons/arrow-right.png \
		icons/media-record-inactive.png \
		icons/arrow-left.png \
		icons/arrow-stop.png \
		icons/media-playback-start.png \
		icons/media-record.png \
		icons/SMCcircle.png \
		icons/arrow-cl.png \
		icons/media-skip-forward.png \
		icons/media-playback-stop.png \
		icons/media-seek-forward.png
	/usr/bin/rcc -name robotino-ressources robotino-ressources.qrc -o qrc_robotino-ressources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_robotinowindow.h ui_robotinofeaturewindow.h ui_smcwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_robotinowindow.h ui_robotinofeaturewindow.h ui_smcwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_robotinowindow.h: robotinowindow.ui
	/usr/bin/uic robotinowindow.ui -o ui_robotinowindow.h

ui_robotinofeaturewindow.h: robotinofeaturewindow.ui
	/usr/bin/uic robotinofeaturewindow.ui -o ui_robotinofeaturewindow.h

ui_smcwindow.h: smcwindow.ui
	/usr/bin/uic smcwindow.ui -o ui_smcwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		smcthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		smcthread.h \
		ui_mainwindow.h \
		robotinowindow.h \
		robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h \
		cameraview.h \
		audioview.h \
		accelerometerview.h \
		distancesensorview.h \
		powerview.h \
		robotinofeaturewindow.h \
		smcwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

robotinowindow.o: robotinowindow.cpp robotinowindow.h \
		robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h \
		cameraview.h \
		audioview.h \
		accelerometerview.h \
		distancesensorview.h \
		powerview.h \
		ui_robotinowindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robotinowindow.o robotinowindow.cpp

distancesensorview.o: distancesensorview.cpp robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h \
		distancesensorview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o distancesensorview.o distancesensorview.cpp

accelerometerview.o: accelerometerview.cpp accelerometerview.h \
		robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accelerometerview.o accelerometerview.cpp

robotinoinfo.o: robotinoinfo.cpp robotinoinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robotinoinfo.o robotinoinfo.cpp

powerview.o: powerview.cpp powerview.h \
		robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o powerview.o powerview.cpp

robotino.o: robotino.cpp robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robotino.o robotino.cpp

robotinocamera.o: robotinocamera.cpp robotinocamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robotinocamera.o robotinocamera.cpp

robotinoaudio.o: robotinoaudio.cpp robotinoaudio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robotinoaudio.o robotinoaudio.cpp

audioview.o: audioview.cpp robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h \
		audioview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audioview.o audioview.cpp

robotinofeaturewindow.o: robotinofeaturewindow.cpp ui_robotinofeaturewindow.h \
		robotinofeaturewindow.h \
		audioview.h \
		robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h \
		smcthread.h \
		imageseqview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o robotinofeaturewindow.o robotinofeaturewindow.cpp

cameraview.o: cameraview.cpp cameraview.h \
		robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cameraview.o cameraview.cpp

smcwindow.o: smcwindow.cpp smcwindow.h \
		ui_smcwindow.h \
		actionobservationview.h \
		actionvalueview.h \
		smcthread.h \
		robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smcwindow.o smcwindow.cpp

smcthread.o: smcthread.cpp smcthread.h \
		robotino.h \
		robotinoaudio.h \
		robotinocamera.h \
		robotinoinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o smcthread.o smcthread.cpp

actionobservationview.o: actionobservationview.cpp actionobservationview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o actionobservationview.o actionobservationview.cpp

imageseqview.o: imageseqview.cpp imageseqview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageseqview.o imageseqview.cpp

actionvalueview.o: actionvalueview.cpp actionvalueview.h \
		smcthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o actionvalueview.o actionvalueview.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_robotinowindow.o: moc_robotinowindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robotinowindow.o moc_robotinowindow.cpp

moc_distancesensorview.o: moc_distancesensorview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_distancesensorview.o moc_distancesensorview.cpp

moc_accelerometerview.o: moc_accelerometerview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_accelerometerview.o moc_accelerometerview.cpp

moc_powerview.o: moc_powerview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_powerview.o moc_powerview.cpp

moc_robotino.o: moc_robotino.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robotino.o moc_robotino.cpp

moc_robotinocamera.o: moc_robotinocamera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robotinocamera.o moc_robotinocamera.cpp

moc_robotinoaudio.o: moc_robotinoaudio.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robotinoaudio.o moc_robotinoaudio.cpp

moc_audioview.o: moc_audioview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audioview.o moc_audioview.cpp

moc_robotinofeaturewindow.o: moc_robotinofeaturewindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_robotinofeaturewindow.o moc_robotinofeaturewindow.cpp

moc_cameraview.o: moc_cameraview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cameraview.o moc_cameraview.cpp

moc_smcwindow.o: moc_smcwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_smcwindow.o moc_smcwindow.cpp

moc_smcthread.o: moc_smcthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_smcthread.o moc_smcthread.cpp

moc_actionobservationview.o: moc_actionobservationview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_actionobservationview.o moc_actionobservationview.cpp

moc_imageseqview.o: moc_imageseqview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imageseqview.o moc_imageseqview.cpp

moc_actionvalueview.o: moc_actionvalueview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_actionvalueview.o moc_actionvalueview.cpp

qrc_robotino-ressources.o: qrc_robotino-ressources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_robotino-ressources.o qrc_robotino-ressources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

